---
collections:

  - name: devsec.hardening
    version: 7.6.0

roles:
  - src: geometrylabs.polkadot_health_check
  - src: geometrylabs.polkadot_base
  - src: geometrylabs.polkadot_library
  - src: geometrylabs.cloud_helper
  - src: https://github.com/ansible-community/ansible-consul.git
    name: ansible-consul
    scm: git
    version: master
  - name: envoyproxy
    src: fabiocruzcoelho.envoyproxy